<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductPurchasesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_purchases')->delete();
        
        \DB::table('product_purchases')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => '37',
                'product_name' => 'Fresh Bottles',
                'product_description' => 'This product is very good. Collected from houses.This product is very good. Collected from houses.This product is very good. Collected from houses.This product is very good. Collected from houses.',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '10',
                'buying_price' => '600',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-13 21:57:35',
                'updated_at' => '2023-04-13 21:57:35',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => '37',
                'product_name' => 'Plastics',
                'product_description' => 'This is a product Description',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-14 17:20:54',
                'updated_at' => '2023-04-14 17:20:54',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => '37',
                'product_name' => 'coke bottles',
                'product_description' => 'this product is usefull',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '3',
                'buying_price' => '180',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-15 07:49:51',
                'updated_at' => '2023-04-15 07:49:51',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => '37',
                'product_name' => 'Plastic boxes',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 01:42:35',
                'updated_at' => '2022-01-15 01:42:35',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => '26',
                'product_name' => 'plastic balti',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '4',
                'buying_price' => '240',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 01:43:38',
                'updated_at' => '2023-04-16 01:43:38',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => '26',
                'product_name' => 'plastic jug',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '8',
                'buying_price' => '480',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 01:44:26',
                'updated_at' => '2023-04-16 01:44:26',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => '25',
                'product_name' => 'bottles',
                'product_description' => 'all products are good quality',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:05:35',
                'updated_at' => '2023-04-16 02:05:35',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => '25',
                'product_name' => 'Plastic Jug',
                'product_description' => 'This Product is very hard and useful',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '3',
                'buying_price' => '180',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:07:03',
                'updated_at' => '2023-04-16 02:07:03',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => '25',
                'product_name' => 'Bottles',
                'product_description' => 'Products are good quality and usefull',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '8',
                'buying_price' => '480',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:08:36',
                'updated_at' => '2023-04-16 02:08:36',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => '24',
                'product_name' => 'Dustbin',
                'product_description' => 'All are usefull',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '7',
                'buying_price' => '420',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:29:40',
                'updated_at' => '2023-04-16 02:29:40',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => '24',
                'product_name' => 'Plastic Toys',
                'product_description' => 'All products are good quality',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '10',
                'buying_price' => '600',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:30:49',
                'updated_at' => '2023-04-16 02:30:49',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => '24',
                'product_name' => 'Boxes',
                'product_description' => 'Products can be used for recycle',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '3',
                'buying_price' => '180',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:32:11',
                'updated_at' => '2023-04-16 02:32:11',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => '23',
                'product_name' => 'One time used Plastics',
                'product_description' => 'Products quality is Good',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '7',
                'buying_price' => '420',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:41:23',
                'updated_at' => '2023-04-16 02:41:23',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => '23',
                'product_name' => 'Bottles',
                'product_description' => 'product are usefull',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:42:47',
                'updated_at' => '2023-04-16 02:42:47',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => '23',
                'product_name' => 'Bottles',
                'product_description' => 'Bottles can be recycle',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '6',
                'buying_price' => '360',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:43:36',
                'updated_at' => '2023-04-16 02:43:36',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => '23',
                'product_name' => 'Buskets',
                'product_description' => 'All products are good',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '4',
                'buying_price' => '320',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:45:05',
                'updated_at' => '2023-04-16 02:45:05',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => '23',
                'product_name' => 'Jug',
                'product_description' => 'Products can be recycle',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:46:01',
                'updated_at' => '2023-04-16 02:46:01',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => '22',
                'product_name' => 'Plates',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '2',
                'product_price' => '80',
                'product_weight' => '7',
                'buying_price' => '560',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:56:28',
                'updated_at' => '2023-04-16 02:56:28',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => '22',
                'product_name' => 'Bottles',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '7',
                'buying_price' => '360',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:58:08',
                'updated_at' => '2023-04-16 02:58:08',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => '22',
                'product_name' => 'Boxes',
                'product_description' => 'Products are fresh and useful',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 02:59:09',
                'updated_at' => '2023-04-16 02:59:09',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => '22',
                'product_name' => 'Plates and glasses',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '8',
                'buying_price' => '480',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:00:02',
                'updated_at' => '2023-04-16 03:00:02',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => '22',
                'product_name' => 'Dishes',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '4',
                'buying_price' => '240',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:00:53',
                'updated_at' => '2023-04-16 03:00:53',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => '21',
                'product_name' => 'Buskets',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '10',
                'buying_price' => '600',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:36:08',
                'updated_at' => '2023-04-16 03:36:08',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => '21',
                'product_name' => 'Toys',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '5',
                'buying_price' => '300',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:36:49',
                'updated_at' => '2023-04-16 03:36:49',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => '21',
                'product_name' => 'plates, glasses and spoons',
                'product_description' => 'products are good',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '7',
                'buying_price' => '420',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2022-01-05 03:38:23',
                'updated_at' => '2023-04-16 03:38:23',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => '21',
                'product_name' => 'Lights',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '12',
                'buying_price' => '720',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:39:03',
                'updated_at' => '2023-04-16 03:39:03',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => '21',
                'product_name' => 'Spoons',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '4',
                'buying_price' => '240',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 03:39:51',
                'updated_at' => '2023-04-16 03:39:51',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => '20',
                'product_name' => '7UP',
                'product_description' => 'Product are good',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '15',
                'buying_price' => '900',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 05:24:29',
                'updated_at' => '2023-04-16 05:24:29',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => '20',
                'product_name' => 'Busket',
                'product_description' => 'Product are good and fresh',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '3',
                'buying_price' => '180',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 05:25:17',
                'updated_at' => '2023-04-16 05:25:17',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => '20',
                'product_name' => 'Boxes',
                'product_description' => 'Product are good',
                'product_category_id' => '3',
                'product_price' => '60',
                'product_weight' => '8',
                'buying_price' => '480',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 05:26:19',
                'updated_at' => '2023-04-16 05:26:19',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => '20',
                'product_name' => 'Lichi Drinks',
                'product_description' => 'Product are good and recycle',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '6',
                'buying_price' => '360',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 05:27:23',
                'updated_at' => '2023-04-16 05:27:23',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => '20',
                'product_name' => 'Bottles',
                'product_description' => 'Product are good and fresh',
                'product_category_id' => '1',
                'product_price' => '60',
                'product_weight' => '7',
                'buying_price' => '420',
                'image' => NULL,
                'status' => 'bought',
                'created_at' => '2023-04-16 05:28:38',
                'updated_at' => '2023-04-16 05:28:38',
            ),
        ));
        
        
    }
}