<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 2,
                'product_name' => 'Fresh Bottles',
                'product_description' => 'This product is very good. Collected from houses.This product is very good. Collected from houses.This product is very good. Collected from houses.This product is very good. Collected from houses.',
                'product_category_id' => '1',
                'product_weight' => '10',
                'product_price' => '60',
                'buying_price' => '600',
                'selling_price' => '790',
                'image1' => '1681423055.jpg',
                'image2' => '1681423055.jpg',
                'image3' => '1681423055.jpg',
                'status' => 'posted',
                'sale_status' => 'sold',
                'created_at' => '2023-04-13 21:57:35',
                'updated_at' => '2023-04-13 21:57:35',
            ),
            1 => 
            array (
                'id' => 3,
                'product_name' => 'Plastics',
                'product_description' => 'This is a product Description',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '400',
                'image1' => '1681492854.webp',
                'image2' => '1681492854.webp',
                'image3' => '1681492854.webp',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-14 17:20:54',
                'updated_at' => '2023-04-14 17:20:54',
            ),
            2 => 
            array (
                'id' => 4,
                'product_name' => 'coke bottles',
                'product_description' => 'this product is usefull',
                'product_category_id' => '1',
                'product_weight' => '3',
                'product_price' => '60',
                'buying_price' => '180',
                'selling_price' => '200',
                'image1' => '1681544991.jpg',
                'image2' => '1681544991.jpeg',
                'image3' => '1681544991.jpeg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-15 07:49:51',
                'updated_at' => '2023-04-15 07:49:51',
            ),
            3 => 
            array (
                'id' => 5,
                'product_name' => 'Plastic boxes',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '350',
                'image1' => '1681609355.jpg',
                'image2' => '1681609355.jpg',
                'image3' => '1681609355.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 01:42:35',
                'updated_at' => '2023-04-16 01:42:35',
            ),
            4 => 
            array (
                'id' => 6,
                'product_name' => 'plastic balti',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'buying_price' => '240',
                'selling_price' => '280',
                'image1' => '1681609418.jpg',
                'image2' => '1681609419.jpg',
                'image3' => '1681609419.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 01:43:38',
                'updated_at' => '2023-04-16 01:43:39',
            ),
            5 => 
            array (
                'id' => 7,
                'product_name' => 'plastic jug',
                'product_description' => NULL,
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'buying_price' => '480',
                'selling_price' => '500',
                'image1' => '1681609465.jpg',
                'image2' => '1681609466.jpg',
                'image3' => '1681609466.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 01:44:25',
                'updated_at' => '2023-04-16 01:44:26',
            ),
            6 => 
            array (
                'id' => 8,
                'product_name' => 'bottles',
                'product_description' => 'all products are good quality',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '350',
                'image1' => '1681610735.jpg',
                'image2' => '1681610736.jpg',
                'image3' => '1681610736.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:05:35',
                'updated_at' => '2023-04-16 02:05:36',
            ),
            7 => 
            array (
                'id' => 9,
                'product_name' => 'Plastic Jug',
                'product_description' => 'This Product is very hard and useful',
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'buying_price' => '180',
                'selling_price' => '200',
                'image1' => '1681610823.jpg',
                'image2' => '1681610823.jpg',
                'image3' => '1681610823.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:07:03',
                'updated_at' => '2023-04-16 02:07:03',
            ),
            8 => 
            array (
                'id' => 10,
                'product_name' => 'Bottles',
                'product_description' => 'Products are good quality and usefull',
                'product_category_id' => '1',
                'product_weight' => '8',
                'product_price' => '60',
                'buying_price' => '480',
                'selling_price' => '520',
                'image1' => '1681610916.jpg',
                'image2' => '1681610916.jpg',
                'image3' => '1681610916.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:08:36',
                'updated_at' => '2023-04-16 02:08:36',
            ),
            9 => 
            array (
                'id' => 11,
                'product_name' => 'Dustbin',
                'product_description' => 'All are usefull',
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'buying_price' => '420',
                'selling_price' => '500',
                'image1' => '1681612180.jpg',
                'image2' => '1681612181.jpg',
                'image3' => '1681612181.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:29:40',
                'updated_at' => '2023-04-16 02:29:41',
            ),
            10 => 
            array (
                'id' => 12,
                'product_name' => 'Plastic Toys',
                'product_description' => 'All products are good quality',
                'product_category_id' => '3',
                'product_weight' => '10',
                'product_price' => '60',
                'buying_price' => '600',
                'selling_price' => '650',
                'image1' => '1681612249.jpg',
                'image2' => '1681612250.jpg',
                'image3' => '1681612250.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:30:49',
                'updated_at' => '2023-04-16 02:30:50',
            ),
            11 => 
            array (
                'id' => 13,
                'product_name' => 'Boxes',
                'product_description' => 'Products can be used for recycle',
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'buying_price' => '180',
                'selling_price' => '220',
                'image1' => '1681612331.jpg',
                'image2' => '1681612331.jpg',
                'image3' => '1681612331.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:32:11',
                'updated_at' => '2023-04-16 02:32:11',
            ),
            12 => 
            array (
                'id' => 14,
                'product_name' => 'One time used Plastics',
                'product_description' => 'Products quality is Good',
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'buying_price' => '420',
                'selling_price' => '450',
                'image1' => '1681612883.jpg',
                'image2' => '1681612884.jpg',
                'image3' => '1681612884.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:41:23',
                'updated_at' => '2023-04-16 02:41:24',
            ),
            13 => 
            array (
                'id' => 15,
                'product_name' => 'Bottles',
                'product_description' => 'product are usefull',
                'product_category_id' => '1',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '330',
                'image1' => '1681612967.jfif',
                'image2' => '1681612967.jpg',
                'image3' => '1681612967.jfif',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:42:47',
                'updated_at' => '2023-04-16 02:42:47',
            ),
            14 => 
            array (
                'id' => 16,
                'product_name' => 'Bottles',
                'product_description' => 'Bottles can be recycle',
                'product_category_id' => '1',
                'product_weight' => '6',
                'product_price' => '60',
                'buying_price' => '360',
                'selling_price' => '400',
                'image1' => '1681613016.jpg',
                'image2' => '1681613016.jpg',
                'image3' => '1681613016.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:43:36',
                'updated_at' => '2023-04-16 02:43:36',
            ),
            15 => 
            array (
                'id' => 17,
                'product_name' => 'Buskets',
                'product_description' => 'All products are good',
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'buying_price' => '320',
                'selling_price' => '400',
                'image1' => '1681613105.jpg',
                'image2' => '1681613105.jpg',
                'image3' => '1681613105.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:45:05',
                'updated_at' => '2023-04-16 02:45:05',
            ),
            16 => 
            array (
                'id' => 18,
                'product_name' => 'Jug',
                'product_description' => 'Products can be recycle',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '330',
                'image1' => '1681613161.jpg',
                'image2' => '1681613161.jpg',
                'image3' => '1681613161.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:46:01',
                'updated_at' => '2023-04-16 02:46:01',
            ),
            17 => 
            array (
                'id' => 19,
                'product_name' => 'Plates',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '2',
                'product_weight' => '7',
                'product_price' => '80',
                'buying_price' => '560',
                'selling_price' => '600',
                'image1' => '1681613788.jpg',
                'image2' => '1681613788.jpg',
                'image3' => '1681613788.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:56:28',
                'updated_at' => '2023-04-16 02:56:28',
            ),
            18 => 
            array (
                'id' => 20,
                'product_name' => 'Bottles',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '1',
                'product_weight' => '7',
                'product_price' => '60',
                'buying_price' => '360',
                'selling_price' => '400',
                'image1' => '1681613888.jfif',
                'image2' => '1681613888.jpg',
                'image3' => '1681613889.jfif',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:58:08',
                'updated_at' => '2023-04-16 02:58:09',
            ),
            19 => 
            array (
                'id' => 21,
                'product_name' => 'Boxes',
                'product_description' => 'Products are fresh and useful',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '330',
                'image1' => '1681613949.jpg',
                'image2' => '1681613949.jpg',
                'image3' => '1681613949.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 02:59:09',
                'updated_at' => '2023-04-16 02:59:09',
            ),
            20 => 
            array (
                'id' => 22,
                'product_name' => 'Plates and glasses',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'buying_price' => '480',
                'selling_price' => '530',
                'image1' => '1681614002.jpg',
                'image2' => '1681614002.jpg',
                'image3' => '1681614002.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:00:02',
                'updated_at' => '2023-04-16 03:00:03',
            ),
            21 => 
            array (
                'id' => 23,
                'product_name' => 'Dishes',
                'product_description' => 'Products are good quality and fresh',
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'buying_price' => '240',
                'selling_price' => '280',
                'image1' => '1681614053.jpg',
                'image2' => '1681614053.jpg',
                'image3' => '1681614053.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:00:53',
                'updated_at' => '2023-04-16 03:00:53',
            ),
            22 => 
            array (
                'id' => 24,
                'product_name' => 'Buskets',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_weight' => '10',
                'product_price' => '60',
                'buying_price' => '600',
                'selling_price' => '650',
                'image1' => '1681616168.jpg',
                'image2' => '1681616169.jpg',
                'image3' => '1681616169.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:36:08',
                'updated_at' => '2023-04-16 03:36:09',
            ),
            23 => 
            array (
                'id' => 25,
                'product_name' => 'Toys',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'buying_price' => '300',
                'selling_price' => '330',
                'image1' => '1681616209.jpg',
                'image2' => '1681616209.jpg',
                'image3' => '1681616209.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:36:49',
                'updated_at' => '2023-04-16 03:36:49',
            ),
            24 => 
            array (
                'id' => 26,
                'product_name' => 'plates, glasses and spoons',
                'product_description' => 'products are good',
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'buying_price' => '420',
                'selling_price' => '500',
                'image1' => '1681616303.jpg',
                'image2' => '1681616303.jfif',
                'image3' => '1681616304.jfif',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:38:23',
                'updated_at' => '2023-04-16 03:38:24',
            ),
            25 => 
            array (
                'id' => 27,
                'product_name' => 'Lights',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_weight' => '12',
                'product_price' => '60',
                'buying_price' => '720',
                'selling_price' => '800',
                'image1' => '1681616342.jpg',
                'image2' => '1681616343.jpg',
                'image3' => '1681616343.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:39:02',
                'updated_at' => '2023-04-16 03:39:03',
            ),
            26 => 
            array (
                'id' => 28,
                'product_name' => 'Spoons',
                'product_description' => 'products are fresh and clean',
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'buying_price' => '240',
                'selling_price' => '280',
                'image1' => '1681616391.jpg',
                'image2' => '1681616391.jpg',
                'image3' => '1681616391.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 03:39:51',
                'updated_at' => '2023-04-16 03:39:51',
            ),
            27 => 
            array (
                'id' => 29,
                'product_name' => '7UP',
                'product_description' => 'Product are good',
                'product_category_id' => '1',
                'product_weight' => '15',
                'product_price' => '60',
                'buying_price' => '900',
                'selling_price' => '1000',
                'image1' => '1681622669.jpg',
                'image2' => '1681622669.jpg',
                'image3' => '1681622670.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 05:24:29',
                'updated_at' => '2023-04-16 05:24:30',
            ),
            28 => 
            array (
                'id' => 30,
                'product_name' => 'Busket',
                'product_description' => 'Product are good and fresh',
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'buying_price' => '180',
                'selling_price' => '200',
                'image1' => '1681622717.jpg',
                'image2' => '1681622717.jpg',
                'image3' => '1681622717.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 05:25:17',
                'updated_at' => '2023-04-16 05:25:17',
            ),
            29 => 
            array (
                'id' => 31,
                'product_name' => 'Boxes',
                'product_description' => 'Product are good',
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'buying_price' => '480',
                'selling_price' => '520',
                'image1' => '1681622779.jpg',
                'image2' => '1681622779.jpg',
                'image3' => '1681622779.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 05:26:19',
                'updated_at' => '2023-04-16 05:26:19',
            ),
            30 => 
            array (
                'id' => 32,
                'product_name' => 'Lichi Drinks',
                'product_description' => 'Product are good and recycle',
                'product_category_id' => '1',
                'product_weight' => '6',
                'product_price' => '60',
                'buying_price' => '360',
                'selling_price' => '400',
                'image1' => '1681622843.webp',
                'image2' => '1681622843.webp',
                'image3' => '1681622843.webp',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 05:27:23',
                'updated_at' => '2023-04-16 05:27:23',
            ),
            31 => 
            array (
                'id' => 33,
                'product_name' => 'Bottles',
                'product_description' => 'Product are good and fresh',
                'product_category_id' => '1',
                'product_weight' => '7',
                'product_price' => '60',
                'buying_price' => '420',
                'selling_price' => '500',
                'image1' => '1681622918.jpg',
                'image2' => '1681622918.jpg',
                'image3' => '1681622918.jpg',
                'status' => 'posted',
                'sale_status' => 'available',
                'created_at' => '2023-04-16 05:28:38',
                'updated_at' => '2023-04-16 05:28:38',
            ),
        ));
        
        
    }
}