<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SellRequestsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sell_requests')->delete();
        
        \DB::table('sell_requests')->insert(array (
            0 => 
            array (
                'id' => 1,
                'seller_id' => '37',
                'address' => 'Dhanmondi,Shongkor,127/2',
                'product_name' => 'Fresh Bottles',
                'product_category_id' => '1',
                'product_weight' => '10',
                'product_price' => '60',
                'total_price' => '600',
                'image' => '1681420494.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-13 21:14:54',
                'updated_at' => '2023-04-13 21:48:10',
            ),
            1 => 
            array (
                'id' => 2,
                'seller_id' => '37',
                'address' => 'Mohammadpud,katashur,2/326',
                'product_name' => 'Plastics',
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681422214.webp',
                'status' => 'assigned',
                'reject_reason' => NULL,
                'created_at' => '2023-04-13 21:43:34',
                'updated_at' => '2023-04-16 01:38:05',
            ),
            2 => 
            array (
                'id' => 3,
                'seller_id' => '37',
                'address' => 'Dhanmondi,Shukrabad,4/150',
                'product_name' => 'Plates',
                'product_category_id' => '2',
                'product_weight' => '7',
                'product_price' => '80',
                'total_price' => '560',
                'image' => '1681422277.jpg',
                'status' => 'assigned',
                'reject_reason' => NULL,
                'created_at' => '2023-04-13 21:44:37',
                'updated_at' => '2023-04-13 21:45:28',
            ),
            3 => 
            array (
                'id' => 4,
                'seller_id' => '37',
                'address' => 'Newmarket',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '3',
                'product_price' => '60',
                'total_price' => '180',
                'image' => '1681544392.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-15 07:39:52',
                'updated_at' => '2023-04-15 07:42:37',
            ),
            4 => 
            array (
                'id' => 5,
                'seller_id' => '26',
                'address' => 'bashundhara sector 2',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => '240',
                'image' => '1681608929.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 01:35:29',
                'updated_at' => '2023-04-16 01:39:47',
            ),
            5 => 
            array (
                'id' => 6,
                'seller_id' => '26',
                'address' => 'Bashundhara sector 2',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'total_price' => '480',
                'image' => '1681608991.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 01:36:31',
                'updated_at' => '2023-04-16 01:39:41',
            ),
            6 => 
            array (
                'id' => 7,
                'seller_id' => '25',
                'address' => 'Puran Dhaka',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681609951.jpg',
                'status' => 'assigned',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 01:52:31',
                'updated_at' => '2023-04-16 02:02:37',
            ),
            7 => 
            array (
                'id' => 8,
                'seller_id' => '25',
                'address' => 'Agargoan',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'total_price' => '180',
                'image' => '1681609998.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 01:53:18',
                'updated_at' => '2023-04-16 02:04:04',
            ),
            8 => 
            array (
                'id' => 9,
                'seller_id' => '25',
                'address' => 'Dhanmondi 2',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '8',
                'product_price' => '60',
                'total_price' => '480',
                'image' => '1681610028.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 01:53:48',
                'updated_at' => '2023-04-16 02:03:59',
            ),
            9 => 
            array (
                'id' => 10,
                'seller_id' => '24',
                'address' => 'panthopoth',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '10',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681611089.jpg',
                'status' => 'rejected',
                'reject_reason' => 'all information should be written',
                'created_at' => '2023-04-16 02:11:29',
                'updated_at' => '2023-04-16 02:15:51',
            ),
            10 => 
            array (
                'id' => 11,
                'seller_id' => '24',
                'address' => 'Panthopath',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681611151.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:12:31',
                'updated_at' => '2023-04-16 02:18:33',
            ),
            11 => 
            array (
                'id' => 12,
                'seller_id' => '24',
                'address' => 'Panthopath',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681611152.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:12:32',
                'updated_at' => '2023-04-16 02:18:29',
            ),
            12 => 
            array (
                'id' => 13,
                'seller_id' => '24',
                'address' => 'panthopath',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681611285.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:14:45',
                'updated_at' => '2023-04-16 02:18:24',
            ),
            13 => 
            array (
                'id' => 14,
                'seller_id' => '24',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681611711.jpg',
                'status' => 'completed',
                'reject_reason' => 'not good',
                'created_at' => '2023-04-16 02:21:51',
                'updated_at' => '2023-04-16 02:28:02',
            ),
            14 => 
            array (
                'id' => 15,
                'seller_id' => '24',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'total_price' => '420',
                'image' => '1681611768.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:22:48',
                'updated_at' => '2023-04-16 02:27:55',
            ),
            15 => 
            array (
                'id' => 16,
                'seller_id' => '24',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '10',
                'product_price' => '60',
                'total_price' => '600',
                'image' => '1681611862.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:24:22',
                'updated_at' => '2023-04-16 02:27:50',
            ),
            16 => 
            array (
                'id' => 17,
                'seller_id' => '24',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'total_price' => '180',
                'image' => '1681611896.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:24:56',
                'updated_at' => '2023-04-16 02:39:21',
            ),
            17 => 
            array (
                'id' => 18,
                'seller_id' => '23',
                'address' => 'Zigatola',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'total_price' => '420',
                'image' => '1681612421.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:33:41',
                'updated_at' => '2023-04-16 02:39:30',
            ),
            18 => 
            array (
                'id' => 19,
                'seller_id' => '23',
                'address' => 'Zigatola',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681612457.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:34:17',
                'updated_at' => '2023-04-16 02:39:17',
            ),
            19 => 
            array (
                'id' => 20,
                'seller_id' => '23',
                'address' => 'Zigatola',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '6',
                'product_price' => '60',
                'total_price' => '360',
                'image' => '1681612482.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:34:42',
                'updated_at' => '2023-04-16 02:39:26',
            ),
            20 => 
            array (
                'id' => 21,
                'seller_id' => '23',
                'address' => 'Zigatola',
                'product_name' => NULL,
                'product_category_id' => '2',
                'product_weight' => '4',
                'product_price' => '80',
                'total_price' => '320',
                'image' => '1681612517.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:35:17',
                'updated_at' => '2023-04-16 02:39:12',
            ),
            21 => 
            array (
                'id' => 22,
                'seller_id' => '23',
                'address' => 'Zigatola',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681612559.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:35:59',
                'updated_at' => '2023-04-16 02:54:51',
            ),
            22 => 
            array (
                'id' => 23,
                'seller_id' => '22',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '2',
                'product_weight' => '7',
                'product_price' => '80',
                'total_price' => '560',
                'image' => '1681613319.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:48:39',
                'updated_at' => '2023-04-16 02:54:41',
            ),
            23 => 
            array (
                'id' => 24,
                'seller_id' => '22',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '6',
                'product_price' => '60',
                'total_price' => '360',
                'image' => '1681613345.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:49:05',
                'updated_at' => '2023-04-16 02:54:47',
            ),
            24 => 
            array (
                'id' => 25,
                'seller_id' => '22',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681613376.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:49:36',
                'updated_at' => '2023-04-16 02:54:36',
            ),
            25 => 
            array (
                'id' => 26,
                'seller_id' => '22',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'total_price' => '480',
                'image' => '1681613432.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:50:32',
                'updated_at' => '2023-04-16 02:54:31',
            ),
            26 => 
            array (
                'id' => 27,
                'seller_id' => '22',
                'address' => 'Banani',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => '240',
                'image' => '1681613470.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 02:51:10',
                'updated_at' => '2023-04-16 03:34:42',
            ),
            27 => 
            array (
                'id' => 28,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '10',
                'product_price' => '60',
                'total_price' => '600',
                'image' => '1681615220.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:20:20',
                'updated_at' => '2023-04-16 03:34:37',
            ),
            28 => 
            array (
                'id' => 29,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681615367.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:22:47',
                'updated_at' => '2023-04-16 03:34:03',
            ),
            29 => 
            array (
                'id' => 30,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '7',
                'product_price' => '60',
                'total_price' => '420',
                'image' => '1681615415.jfif',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:23:35',
                'updated_at' => '2023-04-16 03:33:54',
            ),
            30 => 
            array (
                'id' => 31,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '12',
                'product_price' => '60',
                'total_price' => '720',
                'image' => '1681615449.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:24:09',
                'updated_at' => '2023-04-16 03:33:45',
            ),
            31 => 
            array (
                'id' => 32,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '4',
                'product_price' => '60',
                'total_price' => '240',
                'image' => '1681615478.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:24:38',
                'updated_at' => '2023-04-16 03:33:35',
            ),
            32 => 
            array (
                'id' => 33,
                'seller_id' => '21',
                'address' => 'Dhanmondi',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '7',
                'product_price' => '60',
                'total_price' => 'NaN',
                'image' => '1681615855.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 03:30:55',
                'updated_at' => '2023-04-16 05:23:00',
            ),
            33 => 
            array (
                'id' => 34,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '15',
                'product_price' => '60',
                'total_price' => '900',
                'image' => '1681621176.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 04:59:36',
                'updated_at' => '2023-04-16 05:23:09',
            ),
            34 => 
            array (
                'id' => 35,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '3',
                'product_price' => '60',
                'total_price' => '180',
                'image' => '1681621217.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:00:17',
                'updated_at' => '2023-04-16 05:22:44',
            ),
            35 => 
            array (
                'id' => 36,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '8',
                'product_price' => '60',
                'total_price' => '480',
                'image' => '1681621247.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:00:47',
                'updated_at' => '2023-04-16 05:22:54',
            ),
            36 => 
            array (
                'id' => 37,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '6',
                'product_price' => '60',
                'total_price' => '360',
                'image' => '1681621407.webp',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:03:27',
                'updated_at' => '2023-04-16 05:22:39',
            ),
            37 => 
            array (
                'id' => 38,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '2',
                'product_weight' => '2',
                'product_price' => NULL,
                'total_price' => '0',
                'image' => '1681621473.jpg',
                'status' => 'completed',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:04:33',
                'updated_at' => '2023-04-16 05:22:19',
            ),
            38 => 
            array (
                'id' => 39,
                'seller_id' => '20',
                'address' => 'Bosila',
                'product_name' => NULL,
                'product_category_id' => '1',
                'product_weight' => '7',
                'product_price' => '60',
                'total_price' => '420',
                'image' => '1681621524.jpg',
                'status' => 'assigned',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:05:24',
                'updated_at' => '2023-04-16 05:20:46',
            ),
            39 => 
            array (
                'id' => 40,
                'seller_id' => '19',
                'address' => 'Lalmatia',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '20',
                'product_price' => '60',
                'total_price' => '1200',
                'image' => '1681622990.jpg',
                'status' => 'pending',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:29:50',
                'updated_at' => '2023-04-16 05:29:50',
            ),
            40 => 
            array (
                'id' => 41,
                'seller_id' => '19',
                'address' => 'Lalmatia',
                'product_name' => NULL,
                'product_category_id' => '3',
                'product_weight' => '5',
                'product_price' => '60',
                'total_price' => '300',
                'image' => '1681623195.jpg',
                'status' => 'pending',
                'reject_reason' => NULL,
                'created_at' => '2023-04-16 05:33:15',
                'updated_at' => '2023-04-16 05:33:15',
            ),
        ));
        
        
    }
}