<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role_id' => 1,
                'name' => 'Tanny',
                'email' => 'admin@gmail.com',
                'phone' => '01776203622',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4UQiBwuUQH6pYpmLVKgXoOofXRnVzalgBnpuZNxV3zswScN07cm/6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shongkor,Dhanmondi',
                'image' => '1680286719-c-3.png',
                'gender' => 'Female',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-03-28 07:49:21',
                'updated_at' => '2023-03-31 18:18:39',
            ),
            1 => 
            array (
                'id' => 2,
                'role_id' => 2,
                'name' => 'Tarin Ahmed Shara',
                'email' => 'employee@gmail.com',
                'phone' => '01717608607',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Pbuc2qFWryx0SlDPFh43FulvmWCPq1Z0BUmMyWTy3tdWNTlhA.y5q',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shongkor, Dhanmondi',
                'image' => '1680931086-girl-portrait-16939279.jpg',
                'gender' => 'Female',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-03-28 08:00:53',
                'updated_at' => '2023-04-08 05:18:06',
            ),
            2 => 
            array (
                'id' => 6,
                'role_id' => 3,
                'name' => 'Aishorjo Biswas',
                'email' => 'seler@gmail.com',
                'phone' => '01516760531',
                'email_verified_at' => NULL,
                'password' => '$2y$10$P6fvT0m2IPPXRBnshlzM0ep8aWLuZ.p3FjNdGPDShtcAEOriT8cKW',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shongkor,Dhanmondi',
                'image' => '1680286869-course-author.jpg',
                'gender' => 'Female',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-03-31 18:21:09',
                'updated_at' => '2023-03-31 18:21:09',
            ),
            3 => 
            array (
                'id' => 7,
                'role_id' => 4,
                'name' => 'Bishal Choudhuri',
                'email' => 'buyer@gmail.com',
                'phone' => '01756554564',
                'email_verified_at' => NULL,
                'password' => '$2y$10$i0F4h2phQTS3wJPR6izxWOPzd0bAv0.ve.145ey8hyNUTEDUSplL6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Maymonshing,Dhaka',
                'image' => '1680287589-144946442-frontal-portrait-of-a-serious-looking-businessman.jpg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-03-31 18:33:09',
                'updated_at' => '2023-03-31 18:33:09',
            ),
            4 => 
            array (
                'id' => 9,
                'role_id' => 2,
                'name' => 'Shahin Sikder',
                'email' => 'sikdershahin72@gmail.com',
                'phone' => '01721215790',
                'email_verified_at' => NULL,
                'password' => '$2y$10$X8/QuXczr0d68QN160id7eo3oKjeMqT5M00X9XZs7v9P2Lm7gLklC',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Gulshan',
            'image' => '1680931207-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:20:07',
                'updated_at' => '2023-04-08 05:20:07',
            ),
            5 => 
            array (
                'id' => 10,
                'role_id' => 2,
                'name' => 'Samia Rahman',
                'email' => 'rahmansamia837@gmail.com',
                'phone' => '01310275656',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MBjXETS5Q0fLqWUlaRoFd.e7QyTjGwPz6T9YXP/Qr.flv00XvZAem',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Lalmatia',
            'image' => '1680931822-R (3).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:30:22',
                'updated_at' => '2023-04-08 05:30:22',
            ),
            6 => 
            array (
                'id' => 11,
                'role_id' => 2,
                'name' => 'Rakibul Hasan Rakib',
                'email' => 'rakib.sub.ug02@gmail.com',
                'phone' => '01760828440',
                'email_verified_at' => NULL,
                'password' => '$2y$10$j7wnJBRufunpHhoKCrOCLuNXHpAFQdziTfGz6PRli4QflMlvce7.W',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shahbag',
            'image' => '1680931952-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:32:32',
                'updated_at' => '2023-04-08 05:32:32',
            ),
            7 => 
            array (
                'id' => 12,
                'role_id' => 2,
                'name' => 'Mustafizur Rahman',
                'email' => 'mustafiz.sub19@gmail.com',
                'phone' => '01773362382',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hKAJ8/w86XcmurFtQwHYge1EilhUuV3eQAQxRgXh1B/xgumCcihxe',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Banani',
            'image' => '1680932071-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:34:31',
                'updated_at' => '2023-04-08 05:34:31',
            ),
            8 => 
            array (
                'id' => 13,
                'role_id' => 2,
                'name' => 'Nabil Morshed',
                'email' => 'nabilmorshed1251@gmail.com',
                'phone' => '01999300563',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sU0XyYRypHMBogXfQQrKAuIn3MuWoEvho45x.TWa8uR0s6f1KTo/i',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Bosila',
            'image' => '1680932333-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:38:53',
                'updated_at' => '2023-04-08 05:38:53',
            ),
            9 => 
            array (
                'id' => 14,
                'role_id' => 2,
                'name' => 'Hasanur Rahman Anik',
                'email' => 'hasanurrahmankabir@gmail.com',
                'phone' => '01796642668',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jsSsNKTRV.XY1KOufeGG2.wfk/qeKX547gB4ht6yTyRgWUD55T8RK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Gulshan 2',
            'image' => '1680932423-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:40:23',
                'updated_at' => '2023-04-08 05:40:23',
            ),
            10 => 
            array (
                'id' => 15,
                'role_id' => 2,
                'name' => 'Abrar Faiyz Chowdhury',
                'email' => 'abrarfaiyzchowdhury@gmail.com',
                'phone' => '01635449125',
                'email_verified_at' => NULL,
                'password' => '$2y$10$l24b20AAzuaLVCBmwLRab.d91fvmi0A4EZ0I4CIuK76eGGxwQN63u',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Farmgate',
            'image' => '1680932534-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:42:14',
                'updated_at' => '2023-04-08 05:42:14',
            ),
            11 => 
            array (
                'id' => 16,
                'role_id' => 2,
                'name' => 'Shabnur Akter',
                'email' => 'shabnurakter578@gmail.com',
                'phone' => '01630910968',
                'email_verified_at' => NULL,
                'password' => '$2y$10$2xZtHrB9JclISFRV4jI/J.QuLGInZahoy4khaY0YT/WhFXDVOXgBu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Zigatola',
            'image' => '1680932733-R (3).jpeg',
                'gender' => 'Female',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:45:33',
                'updated_at' => '2023-04-08 05:45:33',
            ),
            12 => 
            array (
                'id' => 17,
                'role_id' => 2,
                'name' => 'Md. Fahim Faysal',
                'email' => 'fahimfaisalaninda@gmail.com',
                'phone' => '01883685125',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.T63b6Z7E/45rDzDYNbY5eXuzZKikk.cPoYUVw9y.jP9zrbpzE67O',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Agargoan',
            'image' => '1680933352-R (2).jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 05:55:52',
                'updated_at' => '2023-04-08 05:55:52',
            ),
            13 => 
            array (
                'id' => 18,
                'role_id' => 3,
                'name' => 'Md. Mynul Islam',
                'email' => 'mynul7355@gmail.com',
                'phone' => '01763819558',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1sJJXR5iXlJ7ys8OCcO1NeG1JnQdeSflSOEuXykhgCZ/hOr4LCKnW',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Hatirjheel',
                'image' => '1680933680_519348.jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:00:26',
                'updated_at' => '2023-04-08 06:01:20',
            ),
            14 => 
            array (
                'id' => 19,
                'role_id' => 3,
                'name' => 'Kaushik Biswas',
                'email' => 'kaushik.biswas.edu@gmail.com',
                'phone' => '01878270829',
                'email_verified_at' => NULL,
                'password' => '$2y$10$oTNk9cx2cVhrymcJsFI2A.IkLef5zS85UXp.KzaXv1KkXMCDilm3u',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Badda',
                'image' => '1680934062_9171503.jpeg',
                'gender' => 'Male',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:06:57',
                'updated_at' => '2023-04-08 06:07:42',
            ),
            15 => 
            array (
                'id' => 20,
                'role_id' => 3,
                'name' => 'Mst. Tasmiya Islam Anika',
                'email' => 'sardaranika22@gmail.com',
                'phone' => '01602248397',
                'email_verified_at' => NULL,
                'password' => '$2y$10$G1jMcjiIeM7Q.mb7uASHlODbP.B533wm2vTzEaQcj5SoeCP7AngsO',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => '12345678',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:10:45',
                'updated_at' => '2023-04-08 06:10:45',
            ),
            16 => 
            array (
                'id' => 21,
                'role_id' => 3,
                'name' => 'Hasan Mahmud Tahsin',
                'email' => 'hasanmahmudtahsinsub@gmail.com',
                'phone' => '01610027909',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iG9W3QJhtkdEwQmn.P551eCPzUE8StgO6P1ZtKTtCaaczMaIHEJC.',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'purandhaka',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:15:45',
                'updated_at' => '2023-04-08 06:15:45',
            ),
            17 => 
            array (
                'id' => 22,
                'role_id' => 3,
                'name' => 'Farzana Azad',
                'email' => 'farzanaazadp@gmail.com',
                'phone' => '01792038579',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yqPTd03aPTIWxYRi9y15ie7qGlFF/Rs.rWYMxSyXD60ef/I0tWouu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Azimpur',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:22:01',
                'updated_at' => '2023-04-08 06:22:01',
            ),
            18 => 
            array (
                'id' => 23,
                'role_id' => 3,
                'name' => 'Ridwana Majumder',
                'email' => 'ridr471@gmail.com',
                'phone' => '01679010324',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FJrDLQHui7reu/lSiCLDpuHR2zxHCRS202ybcOLaZI0RSMRI4ypXu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Tikatoli',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:23:52',
                'updated_at' => '2023-04-08 06:23:52',
            ),
            19 => 
            array (
                'id' => 24,
                'role_id' => 3,
                'name' => 'Ashikur Rahman',
                'email' => 'ashikurrahman18@gmail.com',
                'phone' => '01759770702',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GPvKrkOGZ6xlqYJQnMVDyuaLGRu7tbl9l10I.IEy1EPJuHDknQqN.',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Newmarket',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:26:34',
                'updated_at' => '2023-04-08 06:26:34',
            ),
            20 => 
            array (
                'id' => 25,
                'role_id' => 3,
                'name' => 'Shon pollock Hawlader',
                'email' => 'shonpollock0@gmail.com',
                'phone' => '01911192302',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1qPiDuOYfNqa6eVbeigC5uVbz4l/l0ANGVSOXqQN0sUV5qibIUec2',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Dhanmondi 32',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:29:28',
                'updated_at' => '2023-04-08 06:29:28',
            ),
            21 => 
            array (
                'id' => 26,
                'role_id' => 3,
                'name' => 'Sakib Mahmud',
                'email' => 'sakib.mahmud.1129@gmail.com',
                'phone' => '01401626878',
                'email_verified_at' => NULL,
                'password' => '$2y$10$y96HSYy9plFFg6LSb11g.O1U6U7l5L5VyRHytCwdA1gf/vOtgRH9W',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Uttara',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:30:50',
                'updated_at' => '2023-04-08 06:30:50',
            ),
            22 => 
            array (
                'id' => 27,
                'role_id' => 4,
                'name' => 'Kamrun Nahar priyanka',
                'email' => 'priyankakamrunnahar@gmail.com',
                'phone' => '01811118048',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OH6j.xwZii52mrU0YJJ5.e3R0VJD.G1tp5NEHJ1yeuis1UF3SCvZW',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Baridhara',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:33:42',
                'updated_at' => '2023-04-08 06:33:42',
            ),
            23 => 
            array (
                'id' => 28,
                'role_id' => 4,
                'name' => 'farjana Akter Dula',
                'email' => 'farjanaakterdula009@gmail.com',
                'phone' => '01688090842',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1jvUrm/UAqn1CUXXGMuph.e3euiocXNIYnFy8H95SnOi05AUsEdqK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'green Road',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:35:17',
                'updated_at' => '2023-04-08 06:35:17',
            ),
            24 => 
            array (
                'id' => 29,
                'role_id' => 4,
                'name' => 'Khadija tasnim Muntaha',
                'email' => 'khadija.tasnim.muntaha@gmail.com',
                'phone' => '01834842472',
                'email_verified_at' => NULL,
                'password' => '$2y$10$y7XWWZUnKmk6gvasq6tXweN9H0IQ01U.1Oow/rnpD0ohJQLc7HMDC',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Tejgaon',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:37:12',
                'updated_at' => '2023-04-08 06:37:12',
            ),
            25 => 
            array (
                'id' => 30,
                'role_id' => 4,
                'name' => 'Sumiya Toma',
                'email' => 'sumiyatoma08@gmail.com',
                'phone' => '01319375075',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ycN3AhXd29FW4uyLUp.Wj.2NBOxcuIu5a4hacmLyUaVO6ZUHVgkgC',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Mirpur 1',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:39:10',
                'updated_at' => '2023-04-08 06:39:10',
            ),
            26 => 
            array (
                'id' => 31,
                'role_id' => 4,
                'name' => 'Akramul Hoque Nahid',
                'email' => 'akramulhoque105@gmail.com',
                'phone' => '01791672105',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YJqEZ1XFRi6Z3y0mRKIg9uEN3YgTB/8797/jZZ1VrZWss63KQ74Eq',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Baily Road',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:41:25',
                'updated_at' => '2023-04-08 06:41:25',
            ),
            27 => 
            array (
                'id' => 32,
                'role_id' => 4,
                'name' => 'Arafat Sorkar',
                'email' => 'arafarsorkar12345@gmail.com',
                'phone' => '01318452438',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wAzEzOzAUjQfjai.5cLjWeKO4YXNo9EX03F1JBxbfL3t7jGmttzBK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Dhanmondi 5',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:43:47',
                'updated_at' => '2023-04-08 06:43:47',
            ),
            28 => 
            array (
                'id' => 33,
                'role_id' => 4,
                'name' => 'Rakibul Islam',
                'email' => 'irakibul347@gmail.com',
                'phone' => '01580815520',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QQpOAoaKfwLKd0g5yvw2Z.JYvafuwKP8..2C.MqocN9BwF4WRs4ZS',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shukrabad',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:46:40',
                'updated_at' => '2023-04-08 06:46:40',
            ),
            29 => 
            array (
                'id' => 34,
                'role_id' => 4,
                'name' => 'Afrin Sultana',
                'email' => 'afrinsultana.su@gmail.com',
                'phone' => '01722408037',
                'email_verified_at' => NULL,
                'password' => '$2y$10$80j5upU7KS4J7zx1KySYBuxH.x5GhCWu9EOUfW07ubN1gSkIbXL0e',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Shyamoli',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:48:41',
                'updated_at' => '2023-04-08 06:48:41',
            ),
            30 => 
            array (
                'id' => 35,
                'role_id' => 4,
                'name' => 'Raian Khan',
                'email' => 'raiankhan1999@gmail.com',
                'phone' => '01777869633',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Ftx66o69LTtF9l6Juchg7e4QtZOMf4EIN1zYL9hwwe8KUkEr9spva',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'address' => 'Jatrabari',
                'image' => NULL,
                'gender' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'created_at' => '2023-04-08 06:50:49',
                'updated_at' => '2023-04-08 06:50:49',
            ),
        ));
        
        
    }
}